# Generated by Django 4.1.6 on 2023-02-12 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyinformation',
            old_name='about',
            new_name='about_company',
        ),
        migrations.RenameField(
            model_name='companyinformation',
            old_name='address',
            new_name='company_address',
        ),
        migrations.RenameField(
            model_name='companyinformation',
            old_name='history',
            new_name='company_history',
        ),
        migrations.RenameField(
            model_name='companyinformation',
            old_name='name',
            new_name='company_name',
        ),
    ]
