# Generated by Django 4.1.6 on 2023-07-08 20:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchaddress',
            name='address_and_phone_number',
        ),
        migrations.AddField(
            model_name='branchaddress',
            name='branch_address',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='branchaddress',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'Enter a valid phone number.')]),
        ),
    ]
