# Generated by Django 4.1.6 on 2023-02-19 07:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_companyinformation_facebook_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinformation',
            name='history_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
