# Generated by Django 4.1.6 on 2023-02-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_companyinformation_history_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinformation',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
