# Generated by Django 4.1.6 on 2023-06-29 02:32

from django.db import migrations


def set_default_plan(apps, schema_editor):
    LevelInformation = apps.get_model('dashboard', 'LevelInformation')
    LevelInformation.objects.filter(plan__isnull=True).update(plan='Premium')


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
    ]
