# Generated by Django 4.1.6 on 2023-06-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_proof_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
