# Generated by Django 4.1.6 on 2023-07-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20230629_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelinformation',
            name='plan',
            field=models.CharField(blank=True, choices=[('Premium', 'Premium'), ('Eureka', 'Eureka')], max_length=9, null=True),
        ),
    ]
