# Generated by Django 4.1.6 on 2023-06-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_payment_payment_proof_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('expected_downlines', models.IntegerField()),
                ('expected_match_bonus', models.IntegerField()),
                ('additional_reward', models.CharField(max_length=225)),
            ],
        ),
    ]
