# Generated by Django 4.1.6 on 2023-05-07 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_useraccountinfo_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
