# Generated by Django 4.1.6 on 2023-03-04 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_payment_payment_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
