# Generated by Django 4.1.6 on 2023-03-18 11:03

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_payment_payment_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='refferer_code_used',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_proof',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
